<?php

namespace Database\Seeders;

use App\Models\Pelanggan;
use Illuminate\Database\Seeder;

class PelangganSeeder extends Seeder
{
    public function run(): void
    {
        $pelanggans = [
            [
                'nama_pelanggan' => 'Nayuda Putri',
                'email' => 'nayuda.putri@gmail.com',
                'no_hp' => '085747534084',
                'alamat' => 'Desa Kemantren',
                'jenis_kelamin' => 'Perempuan',
            ],
            [
                'nama_pelanggan' => 'Andi Saputra',
                'email' => 'andi.saputra@gmail.com',
                'no_hp' => '081234567801',
                'alamat' => 'Jl. Merdeka No. 12',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama_pelanggan' => 'Siti Rahma',
                'email' => 'siti.rahma@gmail.com',
                'no_hp' => '081234567802',
                'alamat' => 'Jl. Kenanga No. 5',
                'jenis_kelamin' => 'Perempuan',
            ],
            [
                'nama_pelanggan' => 'Budi Santoso',
                'email' => 'budi.santoso@gmail.com',
                'no_hp' => '081234567803',
                'alamat' => 'Jl. Melati No. 18',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama_pelanggan' => 'Dewi Lestari',
                'email' => 'dewi.lestari@gmail.com',
                'no_hp' => '081234567804',
                'alamat' => 'Jl. Mawar No. 7',
                'jenis_kelamin' => 'Perempuan',
            ],
            [
                'nama_pelanggan' => 'Rizky Pratama',
                'email' => 'rizky.pratama@gmail.com',
                'no_hp' => '081234567805',
                'alamat' => 'Jl. Sudirman No. 21',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama_pelanggan' => 'Ayu Wulandari',
                'email' => 'ayu.wulandari@gmail.com',
                'no_hp' => '081234567806',
                'alamat' => 'Jl. Diponegoro No. 9',
                'jenis_kelamin' => 'Perempuan',
            ],
            [
                'nama_pelanggan' => 'Fajar Nugroho',
                'email' => 'fajar.nugroho@gmail.com',
                'no_hp' => '081234567807',
                'alamat' => 'Jl. Ahmad Yani No. 14',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama_pelanggan' => 'Intan Permata',
                'email' => 'intan.permata@gmail.com',
                'no_hp' => '081234567808',
                'alamat' => 'Jl. Cempaka No. 4',
                'jenis_kelamin' => 'Perempuan',
            ],
            [
                'nama_pelanggan' => 'Yoga Prasetyo',
                'email' => 'yoga.prasetyo@gmail.com',
                'no_hp' => '081234567809',
                'alamat' => 'Jl. Gatot Subroto No. 33',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama_pelanggan' => 'Maya Sari',
                'email' => 'maya.sari@gmail.com',
                'no_hp' => '081234567810',
                'alamat' => 'Jl. Anggrek No. 11',
                'jenis_kelamin' => 'Perempuan',
            ],
            [
                'nama_pelanggan' => 'Dimas Ramadhan',
                'email' => 'dimas.ramadhan@gmail.com',
                'no_hp' => '081234567811',
                'alamat' => 'Jl. Flamboyan No. 6',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama_pelanggan' => 'Nabila Zahra',
                'email' => 'nabila.zahra@gmail.com',
                'no_hp' => '081234567812',
                'alamat' => 'Jl. Kartini No. 22',
                'jenis_kelamin' => 'Perempuan',
            ],
            [
                'nama_pelanggan' => 'Raka Mahendra',
                'email' => 'raka.mahendra@gmail.com',
                'no_hp' => '081234567813',
                'alamat' => 'Jl. Pahlawan No. 16',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama_pelanggan' => 'Putri Amelia',
                'email' => 'putri.amelia@gmail.com',
                'no_hp' => '081234567814',
                'alamat' => 'Jl. Veteran No. 2',
                'jenis_kelamin' => 'Perempuan',
            ],
            [
                'nama_pelanggan' => 'Arif Hidayat',
                'email' => 'arif.hidayat@gmail.com',
                'no_hp' => '081234567815',
                'alamat' => 'Jl. Sawo No. 8',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama_pelanggan' => 'Lina Marlina',
                'email' => 'lina.marlina@gmail.com',
                'no_hp' => '081234567816',
                'alamat' => 'Jl. Mangga No. 17',
                'jenis_kelamin' => 'Perempuan',
            ],
            [
                'nama_pelanggan' => 'Reza Maulana',
                'email' => 'reza.maulana@gmail.com',
                'no_hp' => '081234567817',
                'alamat' => 'Jl. Rambutan No. 10',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama_pelanggan' => 'Citra Anjani',
                'email' => 'citra.anjani@gmail.com',
                'no_hp' => '081234567818',
                'alamat' => 'Jl. Sakura No. 19',
                'jenis_kelamin' => 'Perempuan',
            ],
            [
                'nama_pelanggan' => 'Galih Prakoso',
                'email' => 'galih.prakoso@gmail.com',
                'no_hp' => '081234567819',
                'alamat' => 'Jl. Teratai No. 3',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama_pelanggan' => 'Rani Oktavia',
                'email' => 'rani.oktavia@gmail.com',
                'no_hp' => '081234567820',
                'alamat' => 'Jl. Dahlia No. 25',
                'jenis_kelamin' => 'Perempuan',
            ],
            [
                'nama_pelanggan' => 'Bagas Firmansyah',
                'email' => 'bagas.firmansyah@gmail.com',
                'no_hp' => '081234567821',
                'alamat' => 'Jl. Kamboja No. 13',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama_pelanggan' => 'Tiara Maharani',
                'email' => 'tiara.maharani@gmail.com',
                'no_hp' => '081234567822',
                'alamat' => 'Jl. Nusa Indah No. 20',
                'jenis_kelamin' => 'Perempuan',
            ],
            [
                'nama_pelanggan' => 'Hendra Wijaya',
                'email' => 'hendra.wijaya@gmail.com',
                'no_hp' => '081234567823',
                'alamat' => 'Jl. Pemuda No. 41',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama_pelanggan' => 'Fitri Handayani',
                'email' => 'fitri.handayani@gmail.com',
                'no_hp' => '081234567824',
                'alamat' => 'Jl. Kasuari No. 15',
                'jenis_kelamin' => 'Perempuan',
            ],
            [
                'nama_pelanggan' => 'Ilham Fauzi',
                'email' => 'ilham.fauzi@gmail.com',
                'no_hp' => '081234567825',
                'alamat' => 'Jl. Elang No. 6',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama_pelanggan' => 'Wulan Safitri',
                'email' => 'wulan.safitri@gmail.com',
                'no_hp' => '081234567826',
                'alamat' => 'Jl. Garuda No. 24',
                'jenis_kelamin' => 'Perempuan',
            ],
            [
                'nama_pelanggan' => 'Taufik Akbar',
                'email' => 'taufik.akbar@gmail.com',
                'no_hp' => '081234567827',
                'alamat' => 'Jl. Rajawali No. 30',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama_pelanggan' => 'Mega Puspita',
                'email' => 'mega.puspita@gmail.com',
                'no_hp' => '081234567828',
                'alamat' => 'Jl. Merpati No. 27',
                'jenis_kelamin' => 'Perempuan',
            ],
            [
                'nama_pelanggan' => 'Farhan Alfarizi',
                'email' => 'farhan.alfarizi@gmail.com',
                'no_hp' => '081234567829',
                'alamat' => 'Jl. Semangka No. 9',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama_pelanggan' => 'Nadia Kirana',
                'email' => 'nadia.kirana@gmail.com',
                'no_hp' => '081234567830',
                'alamat' => 'Jl. Apel No. 31',
                'jenis_kelamin' => 'Perempuan',
            ],
            [
                'nama_pelanggan' => 'Iqbal Maulana',
                'email' => 'iqbal.maulana@gmail.com',
                'no_hp' => '081234567831',
                'alamat' => 'Jl. Durian No. 1',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama_pelanggan' => 'Sarah Amelia',
                'email' => 'sarah.amelia@gmail.com',
                'no_hp' => '081234567832',
                'alamat' => 'Jl. Jeruk No. 28',
                'jenis_kelamin' => 'Perempuan',
            ],
            [
                'nama_pelanggan' => 'Rifki Ananda',
                'email' => 'rifki.ananda@gmail.com',
                'no_hp' => '081234567833',
                'alamat' => 'Jl. Salak No. 32',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama_pelanggan' => 'Vina Maharani',
                'email' => 'vina.maharani@gmail.com',
                'no_hp' => '081234567834',
                'alamat' => 'Jl. Alpukat No. 23',
                'jenis_kelamin' => 'Perempuan',
            ],
            [
                'nama_pelanggan' => 'Rangga Aditya',
                'email' => 'rangga.aditya@gmail.com',
                'no_hp' => '081234567835',
                'alamat' => 'Jl. Kelapa No. 44',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama_pelanggan' => 'Anisa Cahyani',
                'email' => 'anisa.cahyani@gmail.com',
                'no_hp' => '081234567836',
                'alamat' => 'Jl. Pinus No. 35',
                'jenis_kelamin' => 'Perempuan',
            ],
            [
                'nama_pelanggan' => 'Kevin Saputra',
                'email' => 'kevin.saputra@gmail.com',
                'no_hp' => '081234567837',
                'alamat' => 'Jl. Cemara No. 26',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama_pelanggan' => 'Mira Anggraini',
                'email' => 'mira.anggraini@gmail.com',
                'no_hp' => '081234567838',
                'alamat' => 'Jl. Bambu No. 36',
                'jenis_kelamin' => 'Perempuan',
            ],
            [
                'nama_pelanggan' => 'Alvin Kurniawan',
                'email' => 'alvin.kurniawan@gmail.com',
                'no_hp' => '081234567839',
                'alamat' => 'Jl. Jati No. 29',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama_pelanggan' => 'Yuni Astuti',
                'email' => 'yuni.astuti@gmail.com',
                'no_hp' => '081234567840',
                'alamat' => 'Jl. Mahoni No. 40',
                'jenis_kelamin' => 'Perempuan',
            ],
            [
                'nama_pelanggan' => 'Agus Setiawan',
                'email' => 'agus.setiawan@gmail.com',
                'no_hp' => '081234567841',
                'alamat' => 'Jl. Cendana No. 50',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama_pelanggan' => 'Laras Kusuma',
                'email' => 'laras.kusuma@gmail.com',
                'no_hp' => '081234567842',
                'alamat' => 'Jl. Kemuning No. 43',
                'jenis_kelamin' => 'Perempuan',
            ],
            [
                'nama_pelanggan' => 'Bayu Anggara',
                'email' => 'bayu.anggara@gmail.com',
                'no_hp' => '081234567843',
                'alamat' => 'Jl. Wijaya Kusuma No. 52',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama_pelanggan' => 'Dinda Aprilia',
                'email' => 'dinda.aprilia@gmail.com',
                'no_hp' => '081234567844',
                'alamat' => 'Jl. Bougenville No. 45',
                'jenis_kelamin' => 'Perempuan',
            ],
            [
                'nama_pelanggan' => 'Reno Saputra',
                'email' => 'reno.saputra@gmail.com',
                'no_hp' => '081234567845',
                'alamat' => 'Jl. Seroja No. 56',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama_pelanggan' => 'Clara Wijaya',
                'email' => 'clara.wijaya@gmail.com',
                'no_hp' => '081234567846',
                'alamat' => 'Jl. Lavender No. 37',
                'jenis_kelamin' => 'Perempuan',
            ],
            [
                'nama_pelanggan' => 'Aditya Nugraha',
                'email' => 'aditya.nugraha@gmail.com',
                'no_hp' => '081234567847',
                'alamat' => 'Jl. Tulip No. 39',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama_pelanggan' => 'Silvia Ramadhani',
                'email' => 'silvia.ramadhani@gmail.com',
                'no_hp' => '081234567848',
                'alamat' => 'Jl. Edelweis No. 42',
                'jenis_kelamin' => 'Perempuan',
            ],
            [
                'nama_pelanggan' => 'Gilang Ramadhan',
                'email' => 'gilang.ramadhan@gmail.com',
                'no_hp' => '081234567849',
                'alamat' => 'Jl. Melur No. 55',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama_pelanggan' => 'Zahra Aulia',
                'email' => 'zahra.aulia@gmail.com',
                'no_hp' => '081234567850',
                'alamat' => 'Jl. Anyelir No. 60',
                'jenis_kelamin' => 'Perempuan',
            ],
        ];

        foreach ($pelanggans as $pelanggan) {
            Pelanggan::updateOrCreate(
                ['email' => $pelanggan['email']],
                $pelanggan
            );
        }
    }
}