<?php

namespace Database\Seeders;

use App\Models\Produk;
use App\Models\Kategori;
use Illuminate\Database\Seeder;

class ProdukSeeder extends Seeder
{
    public function run(): void
    {
        $produks = [
            [
                'nama_produk' => 'AeroFlex Runner',
                'kategori_id' => Kategori::where('nama_kategori', 'Running Shoes')->value('id'),
                'merek' => 'StrideX',
                'ukuran' => '39-44',
                'warna' => 'Hitam',
                'stok' => 35,
                'harga_beli' => 280000,
                'harga_jual' => 450000,
                'deskripsi' => 'Sepatu running ringan untuk aktivitas olahraga harian.',
            ],
            [
                'nama_produk' => 'Urban Classic Sneakers',
                'kategori' => 'Sneakers',
                'merek' => 'UrbanStep',
                'ukuran' => '38-43',
                'warna' => 'Putih',
                'stok' => 42,
                'harga_beli' => 250000,
                'harga_jual' => 399000,
                'deskripsi' => 'Sneakers casual dengan desain clean untuk penggunaan sehari-hari.',
            ],
            [
                'nama_produk' => 'Formal Prime Leather',
                'kategori' => 'Formal Shoes',
                'merek' => 'GentleWalk',
                'ukuran' => '40-44',
                'warna' => 'Coklat',
                'stok' => 20,
                'harga_beli' => 330000,
                'harga_jual' => 575000,
                'deskripsi' => 'Sepatu formal berbahan kulit sintetis premium.',
            ],
            [
                'nama_produk' => 'CourtMax Sport',
                'kategori' => 'Sport Shoes',
                'merek' => 'ActivePro',
                'ukuran' => '39-45',
                'warna' => 'Biru',
                'stok' => 28,
                'harga_beli' => 300000,
                'harga_jual' => 520000,
                'deskripsi' => 'Sepatu sport untuk latihan ringan dan aktivitas outdoor.',
            ],
            [
                'nama_produk' => 'Daily Walk Casual',
                'kategori' => 'Casual Shoes',
                'merek' => 'ComfyStep',
                'ukuran' => '38-43',
                'warna' => 'Abu-abu',
                'stok' => 38,
                'harga_beli' => 220000,
                'harga_jual' => 360000,
                'deskripsi' => 'Sepatu casual nyaman untuk aktivitas harian.',
            ],
            [
                'nama_produk' => 'Velocity Run Pro',
                'kategori' => 'Running Shoes',
                'merek' => 'StrideX',
                'ukuran' => '40-45',
                'warna' => 'Merah',
                'stok' => 25,
                'harga_beli' => 350000,
                'harga_jual' => 625000,
                'deskripsi' => 'Sepatu running dengan bantalan empuk dan sol fleksibel.',
            ],
            [
                'nama_produk' => 'Street Low Sneakers',
                'kategori' => 'Sneakers',
                'merek' => 'UrbanStep',
                'ukuran' => '38-44',
                'warna' => 'Hitam Putih',
                'stok' => 45,
                'harga_beli' => 260000,
                'harga_jual' => 420000,
                'deskripsi' => 'Sneakers low cut untuk tampilan streetwear.',
            ],
            [
                'nama_produk' => 'Oxford Elite Brown',
                'kategori' => 'Formal Shoes',
                'merek' => 'GentleWalk',
                'ukuran' => '39-44',
                'warna' => 'Coklat Tua',
                'stok' => 18,
                'harga_beli' => 370000,
                'harga_jual' => 650000,
                'deskripsi' => 'Sepatu formal model oxford untuk acara resmi.',
            ],
            [
                'nama_produk' => 'FlexFit Training',
                'kategori' => 'Sport Shoes',
                'merek' => 'ActivePro',
                'ukuran' => '39-44',
                'warna' => 'Hijau',
                'stok' => 30,
                'harga_beli' => 290000,
                'harga_jual' => 485000,
                'deskripsi' => 'Sepatu training dengan sol antiselip.',
            ],
            [
                'nama_produk' => 'Canvas Daily Shoes',
                'kategori' => 'Casual Shoes',
                'merek' => 'ComfyStep',
                'ukuran' => '37-42',
                'warna' => 'Cream',
                'stok' => 50,
                'harga_beli' => 180000,
                'harga_jual' => 295000,
                'deskripsi' => 'Sepatu canvas ringan untuk kegiatan santai.',
            ],
            [
                'nama_produk' => 'CloudStep Runner',
                'kategori' => 'Running Shoes',
                'merek' => 'Runova',
                'ukuran' => '39-44',
                'warna' => 'Putih Biru',
                'stok' => 33,
                'harga_beli' => 310000,
                'harga_jual' => 540000,
                'deskripsi' => 'Sepatu lari dengan desain ringan dan breathable.',
            ],
            [
                'nama_produk' => 'Retro High Sneakers',
                'kategori' => 'Sneakers',
                'merek' => 'MetroKicks',
                'ukuran' => '39-44',
                'warna' => 'Putih Merah',
                'stok' => 24,
                'harga_beli' => 320000,
                'harga_jual' => 560000,
                'deskripsi' => 'Sneakers high cut bergaya retro modern.',
            ],
            [
                'nama_produk' => 'Derby Office Black',
                'kategori' => 'Formal Shoes',
                'merek' => 'OfficeMate',
                'ukuran' => '40-45',
                'warna' => 'Hitam',
                'stok' => 22,
                'harga_beli' => 340000,
                'harga_jual' => 590000,
                'deskripsi' => 'Sepatu formal hitam cocok untuk kerja dan acara resmi.',
            ],
            [
                'nama_produk' => 'PowerCourt Sport',
                'kategori' => 'Sport Shoes',
                'merek' => 'ActivePro',
                'ukuran' => '40-45',
                'warna' => 'Putih Hitam',
                'stok' => 26,
                'harga_beli' => 315000,
                'harga_jual' => 530000,
                'deskripsi' => 'Sepatu sport dengan desain stabil untuk latihan.',
            ],
            [
                'nama_produk' => 'Relax Knit Casual',
                'kategori' => 'Casual Shoes',
                'merek' => 'ComfyStep',
                'ukuran' => '38-43',
                'warna' => 'Navy',
                'stok' => 41,
                'harga_beli' => 230000,
                'harga_jual' => 375000,
                'deskripsi' => 'Sepatu casual knit dengan bahan lentur dan nyaman.',
            ],
            [
                'nama_produk' => 'Marathon Lite',
                'kategori' => 'Running Shoes',
                'merek' => 'Runova',
                'ukuran' => '39-45',
                'warna' => 'Abu-abu',
                'stok' => 29,
                'harga_beli' => 340000,
                'harga_jual' => 599000,
                'deskripsi' => 'Sepatu running untuk latihan jarak menengah.',
            ],
            [
                'nama_produk' => 'Neo Street Sneakers',
                'kategori' => 'Sneakers',
                'merek' => 'MetroKicks',
                'ukuran' => '38-44',
                'warna' => 'Hitam',
                'stok' => 47,
                'harga_beli' => 270000,
                'harga_jual' => 430000,
                'deskripsi' => 'Sneakers street style dengan desain simpel.',
            ],
            [
                'nama_produk' => 'Classic Monk Strap',
                'kategori' => 'Formal Shoes',
                'merek' => 'OfficeMate',
                'ukuran' => '40-44',
                'warna' => 'Coklat',
                'stok' => 16,
                'harga_beli' => 390000,
                'harga_jual' => 690000,
                'deskripsi' => 'Sepatu formal model monk strap untuk tampilan elegan.',
            ],
            [
                'nama_produk' => 'AirMove Sport',
                'kategori' => 'Sport Shoes',
                'merek' => 'FitRun',
                'ukuran' => '39-44',
                'warna' => 'Orange',
                'stok' => 27,
                'harga_beli' => 285000,
                'harga_jual' => 470000,
                'deskripsi' => 'Sepatu sport ringan untuk olahraga harian.',
            ],
            [
                'nama_produk' => 'Slip On Everyday',
                'kategori' => 'Casual Shoes',
                'merek' => 'ComfyStep',
                'ukuran' => '38-43',
                'warna' => 'Hitam',
                'stok' => 52,
                'harga_beli' => 190000,
                'harga_jual' => 315000,
                'deskripsi' => 'Sepatu slip on praktis dan nyaman dipakai.',
            ],
            [
                'nama_produk' => 'RoadRunner Speed',
                'kategori' => 'Running Shoes',
                'merek' => 'FitRun',
                'ukuran' => '40-45',
                'warna' => 'Kuning',
                'stok' => 21,
                'harga_beli' => 360000,
                'harga_jual' => 640000,
                'deskripsi' => 'Sepatu running dengan grip kuat untuk jalanan.',
            ],
            [
                'nama_produk' => 'Minimal White Sneakers',
                'kategori' => 'Sneakers',
                'merek' => 'UrbanStep',
                'ukuran' => '37-43',
                'warna' => 'Putih',
                'stok' => 60,
                'harga_beli' => 240000,
                'harga_jual' => 390000,
                'deskripsi' => 'Sneakers putih minimalis untuk outfit casual.',
            ],
            [
                'nama_produk' => 'Business Leather Black',
                'kategori' => 'Formal Shoes',
                'merek' => 'GentleWalk',
                'ukuran' => '40-45',
                'warna' => 'Hitam',
                'stok' => 19,
                'harga_beli' => 400000,
                'harga_jual' => 720000,
                'deskripsi' => 'Sepatu formal kulit sintetis untuk kebutuhan bisnis.',
            ],
            [
                'nama_produk' => 'GymFlex Trainer',
                'kategori' => 'Sport Shoes',
                'merek' => 'FitRun',
                'ukuran' => '39-44',
                'warna' => 'Abu Hitam',
                'stok' => 34,
                'harga_beli' => 305000,
                'harga_jual' => 515000,
                'deskripsi' => 'Sepatu training untuk gym dan aktivitas fitness.',
            ],
            [
                'nama_produk' => 'Weekend Loafers',
                'kategori' => 'Casual Shoes',
                'merek' => 'DailyMode',
                'ukuran' => '39-44',
                'warna' => 'Coklat Muda',
                'stok' => 25,
                'harga_beli' => 260000,
                'harga_jual' => 430000,
                'deskripsi' => 'Loafers casual untuk aktivitas santai dan semi formal.',
            ],
            [
                'nama_produk' => 'SprintCore Runner',
                'kategori' => 'Running Shoes',
                'merek' => 'StrideX',
                'ukuran' => '39-45',
                'warna' => 'Biru Tua',
                'stok' => 31,
                'harga_beli' => 325000,
                'harga_jual' => 555000,
                'deskripsi' => 'Sepatu lari dengan dukungan bantalan empuk.',
            ],
            [
                'nama_produk' => 'Chunky Wave Sneakers',
                'kategori' => 'Sneakers',
                'merek' => 'MetroKicks',
                'ukuran' => '38-44',
                'warna' => 'Putih Abu',
                'stok' => 36,
                'harga_beli' => 330000,
                'harga_jual' => 580000,
                'deskripsi' => 'Sneakers chunky dengan desain trendi.',
            ],
            [
                'nama_produk' => 'Executive Brown Derby',
                'kategori' => 'Formal Shoes',
                'merek' => 'OfficeMate',
                'ukuran' => '40-44',
                'warna' => 'Coklat',
                'stok' => 14,
                'harga_beli' => 380000,
                'harga_jual' => 675000,
                'deskripsi' => 'Sepatu derby formal untuk tampilan profesional.',
            ],
            [
                'nama_produk' => 'ActiveZone Court',
                'kategori' => 'Sport Shoes',
                'merek' => 'ActivePro',
                'ukuran' => '39-45',
                'warna' => 'Putih Biru',
                'stok' => 32,
                'harga_beli' => 310000,
                'harga_jual' => 525000,
                'deskripsi' => 'Sepatu sport untuk latihan indoor dan outdoor.',
            ],
            [
                'nama_produk' => 'EasyStep Slip On',
                'kategori' => 'Casual Shoes',
                'merek' => 'DailyMode',
                'ukuran' => '38-43',
                'warna' => 'Abu-abu',
                'stok' => 44,
                'harga_beli' => 200000,
                'harga_jual' => 330000,
                'deskripsi' => 'Sepatu slip on sederhana untuk pemakaian harian.',
            ],
            [
                'nama_produk' => 'TrailRun Outdoor',
                'kategori' => 'Running Shoes',
                'merek' => 'Runova',
                'ukuran' => '40-45',
                'warna' => 'Hijau Hitam',
                'stok' => 18,
                'harga_beli' => 390000,
                'harga_jual' => 690000,
                'deskripsi' => 'Sepatu running outdoor dengan grip kuat.',
            ],
            [
                'nama_produk' => 'Skate Low Classic',
                'kategori' => 'Sneakers',
                'merek' => 'UrbanStep',
                'ukuran' => '38-44',
                'warna' => 'Hitam Putih',
                'stok' => 39,
                'harga_beli' => 245000,
                'harga_jual' => 410000,
                'deskripsi' => 'Sneakers model skate dengan sol tebal.',
            ],
            [
                'nama_produk' => 'Formal Shine Black',
                'kategori' => 'Formal Shoes',
                'merek' => 'GentleWalk',
                'ukuran' => '40-44',
                'warna' => 'Hitam Glossy',
                'stok' => 17,
                'harga_beli' => 410000,
                'harga_jual' => 750000,
                'deskripsi' => 'Sepatu formal glossy untuk acara resmi.',
            ],
            [
                'nama_produk' => 'CrossFit Motion',
                'kategori' => 'Sport Shoes',
                'merek' => 'FitRun',
                'ukuran' => '39-44',
                'warna' => 'Merah Hitam',
                'stok' => 23,
                'harga_beli' => 350000,
                'harga_jual' => 610000,
                'deskripsi' => 'Sepatu olahraga untuk training intensitas sedang.',
            ],
            [
                'nama_produk' => 'SoftWalk Casual',
                'kategori' => 'Casual Shoes',
                'merek' => 'DailyMode',
                'ukuran' => '38-43',
                'warna' => 'Cream',
                'stok' => 37,
                'harga_beli' => 215000,
                'harga_jual' => 355000,
                'deskripsi' => 'Sepatu casual dengan insole empuk.',
            ],
            [
                'nama_produk' => 'Endurance Runner',
                'kategori' => 'Running Shoes',
                'merek' => 'StrideX',
                'ukuran' => '39-45',
                'warna' => 'Hitam Biru',
                'stok' => 26,
                'harga_beli' => 365000,
                'harga_jual' => 635000,
                'deskripsi' => 'Sepatu lari untuk latihan rutin dan jarak jauh.',
            ],
            [
                'nama_produk' => 'Campus Sneakers',
                'kategori' => 'Sneakers',
                'merek' => 'MetroKicks',
                'ukuran' => '37-43',
                'warna' => 'Navy',
                'stok' => 48,
                'harga_beli' => 235000,
                'harga_jual' => 385000,
                'deskripsi' => 'Sneakers nyaman untuk pelajar dan mahasiswa.',
            ],
            [
                'nama_produk' => 'Premium Office Tan',
                'kategori' => 'Formal Shoes',
                'merek' => 'OfficeMate',
                'ukuran' => '40-45',
                'warna' => 'Tan',
                'stok' => 15,
                'harga_beli' => 395000,
                'harga_jual' => 710000,
                'deskripsi' => 'Sepatu formal warna tan untuk gaya profesional.',
            ],
            [
                'nama_produk' => 'SportPulse Lite',
                'kategori' => 'Sport Shoes',
                'merek' => 'ActivePro',
                'ukuran' => '39-44',
                'warna' => 'Putih Hijau',
                'stok' => 29,
                'harga_beli' => 295000,
                'harga_jual' => 499000,
                'deskripsi' => 'Sepatu sport ringan dengan desain modern.',
            ],
            [
                'nama_produk' => 'Everyday Moccasin',
                'kategori' => 'Casual Shoes',
                'merek' => 'DailyMode',
                'ukuran' => '39-44',
                'warna' => 'Coklat',
                'stok' => 22,
                'harga_beli' => 255000,
                'harga_jual' => 425000,
                'deskripsi' => 'Sepatu moccasin casual untuk aktivitas santai.',
            ],
        ];

        foreach ($produks as $produk) {
    $namaKategori = $produk['kategori'] ?? 'Sneakers';

    unset($produk['kategori']);

    $kategoriId = Kategori::where('nama_kategori', $namaKategori)->value('id');

    if (!$kategoriId) {
        $kategoriId = Kategori::where('nama_kategori', 'Sneakers')->value('id');
    }

    $produk['kategori_id'] = $kategoriId;

    Produk::updateOrCreate(
        ['nama_produk' => $produk['nama_produk']],
        $produk
    );
}
    }
}
