<?php

namespace Database\Seeders;

use App\Models\Produk;
use App\Models\Kategori;
use Illuminate\Database\Seeder;

class UpdateProdukBrandSeeder extends Seeder
{
    public function run(): void
    {
        $produkBaru = [
            [
                'nama_produk' => 'Nike Revolution 6',
                'kategori' => 'Running Shoes',
                'merek' => 'Nike',
                'ukuran' => '39-44',
                'warna' => 'Hitam',
                'stok' => 35,
                'harga_beli' => 620000,
                'harga_jual' => 850000,
                'deskripsi' => 'Sepatu running Nike yang ringan dan nyaman untuk olahraga harian.',
            ],
            [
                'nama_produk' => 'Adidas Superstar',
                'kategori' => 'Sneakers',
                'merek' => 'Adidas',
                'ukuran' => '38-43',
                'warna' => 'Putih Hitam',
                'stok' => 42,
                'harga_beli' => 850000,
                'harga_jual' => 1150000,
                'deskripsi' => 'Sneakers klasik Adidas dengan desain ikonik untuk penggunaan sehari-hari.',
            ],
            [
                'nama_produk' => 'Clarks Tilden Cap Oxford',
                'kategori' => 'Formal Shoes',
                'merek' => 'Clarks',
                'ukuran' => '40-44',
                'warna' => 'Coklat',
                'stok' => 20,
                'harga_beli' => 900000,
                'harga_jual' => 1250000,
                'deskripsi' => 'Sepatu formal model oxford yang cocok untuk kerja dan acara resmi.',
            ],
            [
                'nama_produk' => 'Nike Court Vision Low',
                'kategori' => 'Sport Shoes',
                'merek' => 'Nike',
                'ukuran' => '39-45',
                'warna' => 'Biru',
                'stok' => 28,
                'harga_beli' => 650000,
                'harga_jual' => 950000,
                'deskripsi' => 'Sepatu sport Nike dengan desain court klasik untuk aktivitas santai dan olahraga ringan.',
            ],
            [
                'nama_produk' => 'Skechers Go Walk',
                'kategori' => 'Casual Shoes',
                'merek' => 'Skechers',
                'ukuran' => '38-43',
                'warna' => 'Abu-abu',
                'stok' => 38,
                'harga_beli' => 650000,
                'harga_jual' => 900000,
                'deskripsi' => 'Sepatu casual Skechers yang nyaman untuk aktivitas harian.',
            ],
            [
                'nama_produk' => 'Adidas Ultraboost Light',
                'kategori' => 'Running Shoes',
                'merek' => 'Adidas',
                'ukuran' => '40-45',
                'warna' => 'Merah',
                'stok' => 25,
                'harga_beli' => 1600000,
                'harga_jual' => 2100000,
                'deskripsi' => 'Sepatu running Adidas dengan bantalan responsif untuk aktivitas lari.',
            ],
            [
                'nama_produk' => 'Vans Old Skool',
                'kategori' => 'Sneakers',
                'merek' => 'Vans',
                'ukuran' => '38-44',
                'warna' => 'Hitam Putih',
                'stok' => 45,
                'harga_beli' => 650000,
                'harga_jual' => 850000,
                'deskripsi' => 'Sneakers Vans klasik dengan desain streetwear yang populer.',
            ],
            [
                'nama_produk' => 'Dr. Martens 1461',
                'kategori' => 'Formal Shoes',
                'merek' => 'Dr. Martens',
                'ukuran' => '39-44',
                'warna' => 'Coklat Tua',
                'stok' => 18,
                'harga_beli' => 1300000,
                'harga_jual' => 1750000,
                'deskripsi' => 'Sepatu formal Dr. Martens dengan desain elegan dan kuat.',
            ],
            [
                'nama_produk' => 'Puma Enzo 2',
                'kategori' => 'Sport Shoes',
                'merek' => 'Puma',
                'ukuran' => '39-44',
                'warna' => 'Hijau',
                'stok' => 30,
                'harga_beli' => 620000,
                'harga_jual' => 880000,
                'deskripsi' => 'Sepatu sport Puma dengan sol nyaman untuk latihan ringan.',
            ],
            [
                'nama_produk' => 'Converse Chuck Taylor All Star',
                'kategori' => 'Casual Shoes',
                'merek' => 'Converse',
                'ukuran' => '37-42',
                'warna' => 'Cream',
                'stok' => 50,
                'harga_beli' => 550000,
                'harga_jual' => 750000,
                'deskripsi' => 'Sepatu Converse canvas klasik untuk tampilan kasual.',
            ],
            [
                'nama_produk' => 'Asics Gel-Kayano',
                'kategori' => 'Running Shoes',
                'merek' => 'Asics',
                'ukuran' => '39-44',
                'warna' => 'Putih Biru',
                'stok' => 33,
                'harga_beli' => 1350000,
                'harga_jual' => 1800000,
                'deskripsi' => 'Sepatu running Asics dengan dukungan stabilitas dan bantalan empuk.',
            ],
            [
                'nama_produk' => 'Nike Air Jordan 1 Mid',
                'kategori' => 'Sneakers',
                'merek' => 'Nike',
                'ukuran' => '39-44',
                'warna' => 'Putih Merah',
                'stok' => 24,
                'harga_beli' => 1700000,
                'harga_jual' => 2300000,
                'deskripsi' => 'Sneakers Nike Air Jordan dengan desain retro yang populer.',
            ],
            [
                'nama_produk' => 'Hush Puppies Gil Slip On',
                'kategori' => 'Formal Shoes',
                'merek' => 'Hush Puppies',
                'ukuran' => '40-45',
                'warna' => 'Hitam',
                'stok' => 22,
                'harga_beli' => 780000,
                'harga_jual' => 1050000,
                'deskripsi' => 'Sepatu formal slip on yang nyaman untuk kerja dan acara semi formal.',
            ],
            [
                'nama_produk' => 'Adidas Grand Court',
                'kategori' => 'Sport Shoes',
                'merek' => 'Adidas',
                'ukuran' => '40-45',
                'warna' => 'Putih Hitam',
                'stok' => 26,
                'harga_beli' => 620000,
                'harga_jual' => 890000,
                'deskripsi' => 'Sepatu sport Adidas dengan desain court sederhana dan nyaman.',
            ],
            [
                'nama_produk' => 'New Balance 574',
                'kategori' => 'Casual Shoes',
                'merek' => 'New Balance',
                'ukuran' => '38-43',
                'warna' => 'Navy',
                'stok' => 41,
                'harga_beli' => 900000,
                'harga_jual' => 1250000,
                'deskripsi' => 'Sepatu New Balance kasual dengan desain klasik dan nyaman.',
            ],
            [
                'nama_produk' => 'New Balance Fresh Foam',
                'kategori' => 'Running Shoes',
                'merek' => 'New Balance',
                'ukuran' => '39-45',
                'warna' => 'Abu-abu',
                'stok' => 29,
                'harga_beli' => 1100000,
                'harga_jual' => 1500000,
                'deskripsi' => 'Sepatu running New Balance dengan bantalan Fresh Foam yang nyaman.',
            ],
            [
                'nama_produk' => 'Nike Air Force 1',
                'kategori' => 'Sneakers',
                'merek' => 'Nike',
                'ukuran' => '38-44',
                'warna' => 'Putih',
                'stok' => 47,
                'harga_beli' => 1200000,
                'harga_jual' => 1650000,
                'deskripsi' => 'Sneakers Nike Air Force 1 dengan desain putih minimalis.',
            ],
            [
                'nama_produk' => 'Bata North Star Formal',
                'kategori' => 'Formal Shoes',
                'merek' => 'Bata',
                'ukuran' => '40-44',
                'warna' => 'Coklat',
                'stok' => 16,
                'harga_beli' => 390000,
                'harga_jual' => 650000,
                'deskripsi' => 'Sepatu formal Bata untuk kebutuhan kerja dan acara resmi.',
            ],
            [
                'nama_produk' => 'Reebok Flexagon Energy',
                'kategori' => 'Sport Shoes',
                'merek' => 'Reebok',
                'ukuran' => '39-44',
                'warna' => 'Orange',
                'stok' => 27,
                'harga_beli' => 580000,
                'harga_jual' => 820000,
                'deskripsi' => 'Sepatu sport Reebok yang cocok untuk latihan ringan dan gym.',
            ],
            [
                'nama_produk' => 'Skechers Arch Fit',
                'kategori' => 'Casual Shoes',
                'merek' => 'Skechers',
                'ukuran' => '38-43',
                'warna' => 'Hitam',
                'stok' => 52,
                'harga_beli' => 850000,
                'harga_jual' => 1200000,
                'deskripsi' => 'Sepatu casual Skechers dengan dukungan arch fit untuk kenyamanan harian.',
            ],
            [
                'nama_produk' => 'Nike Pegasus 40',
                'kategori' => 'Running Shoes',
                'merek' => 'Nike',
                'ukuran' => '40-45',
                'warna' => 'Kuning',
                'stok' => 21,
                'harga_beli' => 1350000,
                'harga_jual' => 1800000,
                'deskripsi' => 'Sepatu running Nike Pegasus untuk latihan lari rutin.',
            ],
            [
                'nama_produk' => 'Adidas Stan Smith',
                'kategori' => 'Sneakers',
                'merek' => 'Adidas',
                'ukuran' => '37-43',
                'warna' => 'Putih',
                'stok' => 60,
                'harga_beli' => 850000,
                'harga_jual' => 1200000,
                'deskripsi' => 'Sneakers Adidas Stan Smith dengan desain putih minimalis.',
            ],
            [
                'nama_produk' => 'Clarks Un Aldric Lace',
                'kategori' => 'Formal Shoes',
                'merek' => 'Clarks',
                'ukuran' => '40-45',
                'warna' => 'Hitam',
                'stok' => 19,
                'harga_beli' => 1000000,
                'harga_jual' => 1400000,
                'deskripsi' => 'Sepatu formal Clarks dengan desain elegan untuk kebutuhan bisnis.',
            ],
            [
                'nama_produk' => 'Under Armour Charged Pursuit',
                'kategori' => 'Sport Shoes',
                'merek' => 'Under Armour',
                'ukuran' => '39-44',
                'warna' => 'Abu Hitam',
                'stok' => 34,
                'harga_beli' => 750000,
                'harga_jual' => 1050000,
                'deskripsi' => 'Sepatu sport Under Armour untuk gym dan aktivitas fitness.',
            ],
            [
                'nama_produk' => 'Skechers Equalizer Slip On',
                'kategori' => 'Casual Shoes',
                'merek' => 'Skechers',
                'ukuran' => '39-44',
                'warna' => 'Coklat Muda',
                'stok' => 25,
                'harga_beli' => 680000,
                'harga_jual' => 950000,
                'deskripsi' => 'Sepatu slip on Skechers yang nyaman untuk aktivitas santai.',
            ],
            [
                'nama_produk' => 'Adidas Duramo SL',
                'kategori' => 'Running Shoes',
                'merek' => 'Adidas',
                'ukuran' => '39-45',
                'warna' => 'Biru Tua',
                'stok' => 31,
                'harga_beli' => 620000,
                'harga_jual' => 890000,
                'deskripsi' => 'Sepatu running Adidas yang ringan untuk olahraga harian.',
            ],
            [
                'nama_produk' => 'Puma RS-X',
                'kategori' => 'Sneakers',
                'merek' => 'Puma',
                'ukuran' => '38-44',
                'warna' => 'Putih Abu',
                'stok' => 36,
                'harga_beli' => 900000,
                'harga_jual' => 1300000,
                'deskripsi' => 'Sneakers Puma dengan desain chunky dan modern.',
            ],
            [
                'nama_produk' => 'Florsheim Midtown Cap Toe',
                'kategori' => 'Formal Shoes',
                'merek' => 'Florsheim',
                'ukuran' => '40-44',
                'warna' => 'Coklat',
                'stok' => 14,
                'harga_beli' => 950000,
                'harga_jual' => 1350000,
                'deskripsi' => 'Sepatu formal Florsheim dengan desain profesional.',
            ],
            [
                'nama_produk' => 'Nike Precision 6',
                'kategori' => 'Sport Shoes',
                'merek' => 'Nike',
                'ukuran' => '39-45',
                'warna' => 'Putih Biru',
                'stok' => 32,
                'harga_beli' => 800000,
                'harga_jual' => 1150000,
                'deskripsi' => 'Sepatu sport Nike untuk latihan indoor dan outdoor.',
            ],
            [
                'nama_produk' => 'Crocs Classic Clog',
                'kategori' => 'Casual Shoes',
                'merek' => 'Crocs',
                'ukuran' => '38-43',
                'warna' => 'Abu-abu',
                'stok' => 44,
                'harga_beli' => 420000,
                'harga_jual' => 650000,
                'deskripsi' => 'Alas kaki casual Crocs yang praktis dan ringan.',
            ],
            [
                'nama_produk' => 'Salomon Speedcross',
                'kategori' => 'Running Shoes',
                'merek' => 'Salomon',
                'ukuran' => '40-45',
                'warna' => 'Hijau Hitam',
                'stok' => 18,
                'harga_beli' => 1450000,
                'harga_jual' => 1950000,
                'deskripsi' => 'Sepatu running outdoor Salomon dengan grip kuat.',
            ],
            [
                'nama_produk' => 'Vans Skate Old Skool',
                'kategori' => 'Sneakers',
                'merek' => 'Vans',
                'ukuran' => '38-44',
                'warna' => 'Hitam Putih',
                'stok' => 39,
                'harga_beli' => 700000,
                'harga_jual' => 950000,
                'deskripsi' => 'Sneakers Vans model skate dengan desain klasik.',
            ],
            [
                'nama_produk' => 'Bata Formal Shine Black',
                'kategori' => 'Formal Shoes',
                'merek' => 'Bata',
                'ukuran' => '40-44',
                'warna' => 'Hitam Glossy',
                'stok' => 17,
                'harga_beli' => 430000,
                'harga_jual' => 720000,
                'deskripsi' => 'Sepatu formal hitam glossy untuk acara resmi.',
            ],
            [
                'nama_produk' => 'Reebok Nano X',
                'kategori' => 'Sport Shoes',
                'merek' => 'Reebok',
                'ukuran' => '39-44',
                'warna' => 'Merah Hitam',
                'stok' => 23,
                'harga_beli' => 950000,
                'harga_jual' => 1350000,
                'deskripsi' => 'Sepatu training Reebok untuk olahraga intensitas sedang.',
            ],
            [
                'nama_produk' => 'Skechers Bobs Squad',
                'kategori' => 'Casual Shoes',
                'merek' => 'Skechers',
                'ukuran' => '38-43',
                'warna' => 'Cream',
                'stok' => 37,
                'harga_beli' => 580000,
                'harga_jual' => 820000,
                'deskripsi' => 'Sepatu casual Skechers dengan bahan ringan dan nyaman.',
            ],
            [
                'nama_produk' => 'Asics Novablast',
                'kategori' => 'Running Shoes',
                'merek' => 'Asics',
                'ukuran' => '39-45',
                'warna' => 'Hitam Biru',
                'stok' => 26,
                'harga_beli' => 1250000,
                'harga_jual' => 1700000,
                'deskripsi' => 'Sepatu running Asics untuk latihan rutin dan jarak menengah.',
            ],
            [
                'nama_produk' => 'New Balance 327',
                'kategori' => 'Sneakers',
                'merek' => 'New Balance',
                'ukuran' => '37-43',
                'warna' => 'Navy',
                'stok' => 48,
                'harga_beli' => 950000,
                'harga_jual' => 1350000,
                'deskripsi' => 'Sneakers New Balance dengan desain retro modern.',
            ],
            [
                'nama_produk' => 'Hush Puppies The Good',
                'kategori' => 'Formal Shoes',
                'merek' => 'Hush Puppies',
                'ukuran' => '40-45',
                'warna' => 'Tan',
                'stok' => 15,
                'harga_beli' => 850000,
                'harga_jual' => 1200000,
                'deskripsi' => 'Sepatu formal Hush Puppies dengan tampilan profesional.',
            ],
            [
                'nama_produk' => 'Puma Flyer Runner',
                'kategori' => 'Sport Shoes',
                'merek' => 'Puma',
                'ukuran' => '39-44',
                'warna' => 'Putih Hijau',
                'stok' => 29,
                'harga_beli' => 600000,
                'harga_jual' => 850000,
                'deskripsi' => 'Sepatu sport Puma ringan dengan desain modern.',
            ],
            [
                'nama_produk' => 'Adidas Adilette Aqua',
                'kategori' => 'Casual Shoes',
                'merek' => 'Adidas',
                'ukuran' => '39-44',
                'warna' => 'Coklat',
                'stok' => 22,
                'harga_beli' => 220000,
                'harga_jual' => 350000,
                'deskripsi' => 'Sandal Adidas yang nyaman untuk aktivitas santai.',
            ],
        ];

        $produkLama = Produk::orderBy('id')->get();

        foreach ($produkLama as $index => $produk) {
            if (!isset($produkBaru[$index])) {
                continue;
            }

            $data = $produkBaru[$index];

            $namaKategori = $data['kategori'] ?? 'Sneakers';
            unset($data['kategori']);

            $kategoriId = Kategori::where('nama_kategori', $namaKategori)->value('id');

            if (!$kategoriId) {
                $kategoriId = Kategori::where('nama_kategori', 'Sneakers')->value('id');
            }

            $data['kategori_id'] = $kategoriId;

            $produk->update($data);
        }
    }
}